### PR TITLE
feat: bandersnatch impl and other fixes

### PR DESCRIPTION
**Pull request by dragan2234**
Dependency fixes and bandersnatch impl taken from https://github.com/hyperledger/besu/blob/main/ethereum/verkletrie/src/main/java/org/hyperledger/besu/ethereum/verkletrie/bandersnatch/Point.java

### CODE REVIEW

**Comment by dragan2234** [comment]
@thomas-quadratic  Looking at the go impl, commitments are defined as Points, and there was already bandersnatch implementation in besu, so copied over that and included in the repo

**Comment by dragan2234** [comment]
Also I think scalarMultiplication is missing for Point.java. Not sure if we need that right now, but something related to Fr is needed for `hash`. Just noting this

**Comment by thomas-quadratic** [comment]
There are 2 things that I am unsure about.
First, by explicitly making commitments as Points instead of the more generic Bytes, I feel that we are coupling Verkle Tries to the implementation of polynomial commitments. Perhaps we should be designing an interface for this? (which is probably needed in any case)
Secondly, Point does not wrap any object from the native lib, but provides its own Java implementation. Does that mean that we will have to implement IPA?

**Comment by dragan2234** [comment]
> First, by explicitly making commitments as Points instead of the more generic Bytes, I feel that we are coupling Verkle Tries to the implementation of polynomial commitments. 

tbh, not sure how decoupled is the implementation of polynomial commitments from verkle tries especially when verifying the proof and testing it. At least that's my conclusion looking at the rust and go implementations.

> Secondly, Point does not wrap any object from the native lib, but provides its own Java implementation. Does that mean that we will have to implement IPA?

I thought native-libs are good for having "helper" functions like calculating the commitment to some values (which is probably enough for us for now).

The main point I ported this PR to our repo is that the guys from Besu implemented this even after the implementation of JNI wrapper of ipa_multipoint.

**I guess the conclusion is to keep this PR here without merging it. Just saving this code, maybe it will be useful.**

Let me know your thoughts @thomas-quadratic

**Comment by dragan2234** [comment]
@thomas-quadratic  Anotoine from besu mentioned that this is needed for verkle tries:
https://github.com/hyperledger/besu/pull/4647#issuecomment-1631853905

**Comment by dragan2234** [comment]
Closing this PR so it doesn't cause confusion. We finally don't need curve implementation in Java, rust JNI is enough

**Pull request closed without merging**
